[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = false

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)"

[directory]
read_only = " 🔓"
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic blue"

[cmd_duration]
min_time = 2
show_milliseconds = false
disabled = false
style = "bold italic red"

[package]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[gradle]
disabled = true

[kotlin]
disabled = true

[docker_context]
symbol = "🐋 "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[python]
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold green"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[nodejs]
disabled = true
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[bun]
disabled = true

[shell]
disabled = true
fish_indicator = "🐟"
zsh_indicator =  "💤"

[lua]
disabled = true

[dart]
disabled = true

[git_status]
disabled = true
